# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to=b'')),
                ('cost', models.CharField(blank=True, max_length=255, null=True, verbose_name='Costing')),
                ('status', models.CharField(blank=True, choices=[('On Rent', 'On Rent'), ('For Sale', 'For Sale')], max_length=255, null=True, verbose_name='Status')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('description', models.TextField(verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
