# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20170719_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_original', models.FileField(upload_to='media/1500449555/', verbose_name='original file upload')),
                ('photo_medium', models.CharField(blank=True, max_length=255)),
                ('photo_thumb', models.CharField(blank=True, max_length=255)),
                ('photo_credits', models.CharField(blank=True, max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Property Listing',
                'verbose_name_plural': 'Property Listings',
            },
        ),
        migrations.AlterModelOptions(
            name='propertylisting',
            options={},
        ),
        migrations.RenameField(
            model_name='propertylisting',
            old_name='title',
            new_name='name',
        ),
    ]
