# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20170719_0732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AlterModelOptions(
            name='propertylisting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Property Listing', 'verbose_name_plural': 'Property Listings'},
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='photo_credits',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='photo_medium',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='photo_original',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/1500449673/', verbose_name='original file upload'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='photo_thumb',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
