# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20170719_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='image',
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='photo_original',
            field=models.FileField(upload_to='media/1500449750/', verbose_name='original file upload'),
        ),
    ]
