# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20170719_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('sub_heading', models.TextField()),
                ('paragraph_text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='photo_original',
            field=models.FileField(upload_to='media/1511165718/', verbose_name='original file upload'),
        ),
    ]
