# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-24 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20171122_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='full name')),
                ('company', models.CharField(max_length=120, verbose_name='company name')),
                ('email', models.EmailField(max_length=120, verbose_name='email address')),
                ('message', models.TextField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='photo_original',
            field=models.FileField(upload_to='media/1511514695/', verbose_name='original file upload'),
        ),
    ]
